### ISSUE TITLE
Remove dependencies on google font

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/nuage#102]
As per the discussion [here](https://github.com/mickael-kerjean/nuage/issues/100), it would be nice to remove the dependency on google font that appears [here](https://github.com/mickael-kerjean/nuage/blob/31f8c273ff40e9174e36a4025497a520d7cb58ca/client/assets/css/reset.scss#L1) and load the font directly from the server instead

*Disclaimer*: I'm not interested in this feature myself but I guess people with privacy concern could make a pull request to change that.

**Comment by Lewiscowles1986** [comment]
If people are in a non-network connective environment Google fonts not embedded like this can actually lead to 30+second timeouts on page load.

**Comment by mickael-kerjean** [comment]
You are right, I didn't consider this use case. The google font is coming from [here](https://github.com/mickael-kerjean/nuage/blob/master/client/assets/css/reset.scss#L1)

**Comment by Lewiscowles1986** [comment]
pull request used ie, ff, edge and chrome output of URL (because google browser sniffs) to fill in the font details. Rather nice local-font fallback built-in I see. Pretty sure that is new.

**Comment by Lewiscowles1986** [comment]
Btw did you know it's not just this font you rely on? Roboto isn't a universal device native font and I'm sure I saw another.

**Comment by mickael-kerjean** [comment]
Nice, you rock! When it comes to fonts this is done on purpose. The idea is to let the browser load the font that's appropriate to the user instead of forcing my own selected font. 

For any apple device "San Francisco" will load great, Android device "Roboto" will do great and for window "Arial" is good enough whereas my linux laptop got some awesome sans-serif font by default.
