### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by nicedreams** [mickael-kerjean/nuage#108]
Excuse my ignorance.  I know how to run nginx and can usually get simple sites and Wordpress running, but can't figure out how to get this to work on my nginx server.  The instructions just say use SSL and there's a docker image (don't want to use docker), but don't know how to get this installed and working.

Is nauge run it's own server and I reverse proxy with nginx?  Made nauge executable but getting this message and can't find file to install via apt in debian:
"./nuage: error while loading shared libraries: libraw.so.19: cannot open shared object file: No such file or directory"

**Comment by nicedreams** [comment]
Assuming nuage is it's own server, still getting libraw.so.19 not found when I go to run it.  I went to https://www.libraw.org/download#stable and did ./configure && make && make install and still not working.  If could point me in the right direction please?

**Comment by mickael-kerjean** [comment]
The recommended installation method is via Docker. If you really don't want to use it, you need to: create your own build and install libraw and libvips. To do that, the instructions are embed within the [Dockerfile](https://github.com/mickael-kerjean/nuage/blob/master/docker/prod/Dockerfile)

**Comment by nicedreams** [comment]
Will try to rebuild lib's and if not work will use Docker.  Thanks.  I need to learn Docker more anyways.

**Comment by mickael-kerjean** [comment]
As I can't see any action needed from my end here, I'm closing the ticket but feel free to comment back and I'll reopen
