### ISSUE TITLE
Photo Size

### ISSUE THREAD

**Issue by palitu** [mickael-kerjean/nuage#109]
Hi, i would like to change the size of the photo that is displayed, to try and get the size of the transfer to around 300kb.

is this a setting that can be changed?  or change the hard code?  I am using linux docker image.

**Comment by mickael-kerjean** [comment]
By default [the client is requesting pictures at the size of the screen](https://github.com/mickael-kerjean/nuage/blob/master/client/pages/viewerpage/imageviewer.js#L263-L277) to avoid wasting bandwidth and the server is changing the dimensions of a [picture on demand](https://github.com/mickael-kerjean/nuage/blob/master/server/services/pipeline.go#L29-L97). 

It's hard to know in advance how heavy will be an image. a 20x20 green image will be much smaller than a large pictures taken from a DSLR. What are you trying to achieve to need "transfer to around 300kb"?

**Comment by mickael-kerjean** [comment]
As I can't see any action needed from my end here, I'm closing the ticket but feel free to comment back and I'll reopen

**Comment by palitu** [comment]
Ok, When pushing photos out to the web, it is typically nice (for self
hosted) to limit the size of the photo, get a balance between
size/resolution and the speed of retrieval.

When i was viewing some photos, they were downloading in the 1.3-1.5 mb
range, which severely impacted the speed in which i could actually view
them.

I would like to set the maximum 'preview' size of a picture, so that i can
limit the time it takes to load an item.

cheers,

**Comment by mickael-kerjean** [comment]
> Ok, When pushing photos out to the web, it is typically nice (for self
hosted) to limit the size of the photo

Nuage is already transcoding your pictures at the best it can. For instance, jpeg thumbnails are 300x300 with a quality parameter of 50 to make them fairly small in size. When viewing a pictures, the same treatment happen except the size is set to the dimension of the screen and quality to 90.

> When i was viewing some photos, they were downloading in the 1.3-1.5 mb
range, which severely impacted the speed in which i could actually view
them.

Personally my pictures load super fast and I don't understand how you can end up downloading 1.3 to 1.5mb. Can you send me some of those pictures for me to test on?

![image](https://user-images.githubusercontent.com/13233076/47477865-0fa35080-d873-11e8-9edf-36e5f49b1124.png)

**Comment by palitu** [comment]
will do, i will have to restart nuage on my server and have a look tomorrow.

cheers,
