### ISSUE TITLE
Does my use case make sense?

### ISSUE THREAD

**Issue by DaniGuardiola** [mickael-kerjean/nuage#110]
I'm working on a freelance project and I want to make it easy for my client to edit the contents of a directory without much hassle. My current idea is to setup a web FTP client, give them a user and a password and let them upload, remove, or edit the title of images in a single folder.

To achieve this I'm looking for a client that allows this:
- Only FTP login
- Only for a hard-coded server (so it's only user and password)

From my understanding after taking a look at some docs, this project allows both things. Now I would like to know if the following nice-to-have features are available:
- Restrict actions so that it's only possible to upload, download, preview, remove or rename files (so no file editing, no creation of new dirs, etc)
- Restrict file types to a whitelist (so that I can allow only png, jpg, etc files to be uploaded)

These two last requirements are optional, but the first two are a must. Thank you :)

**Comment by DaniGuardiola** [comment]
PD: I also need to restrict the access to a single hard-coded directory. I've read that you can set that up on the FTP server directly, I'm just wondering if that can be achieved through nuage as well.

**Comment by DaniGuardiola** [comment]
Oh, one last question, is there any built-in option to automatically optimize images being uploaded? Because I definitely can picture my client uploading 10mb png files that will be displayed as 300x300 haha

**Comment by mickael-kerjean** [comment]
Hello there,

> My current idea is ...... this project allows both things

Yes it does. You can hardcode a few thing in the config and only allow for username and password:. For example, I got [this instance](http://files.kerjean.me) I use for personal stuff where the config.json looks like:
```
{
 .....
 },
    "connections": [
        {
                "type": "sftp",
                "label": "SFTP",
                "hostname":"ip_address_of_my_sftp_server", 
                "passphrase": "",
                "path": "",
                "port": "22",
                "advanced": false
        }
    ]
}
```


> Restrict actions so that it's only possible to upload, download, preview, remove or rename files (so no file editing, no creation of new dirs, etc), Restrict file types to a whitelist

Those aren't part of the project as I had no use case for it. If you want to make it happen, pull request are welcome or I can make it happen for a fee.

> I also need to restrict the access to a single hard-coded directory. I've read that you can set that up on the FTP server directly, I'm just wondering if that can be achieved through nuage as well.

You got 2 way to do that:
1) at the FTP level with a chroot jail. 
2) at the nuage level by setting the path variable in the config.json (the one that was empty on my own instance)

Beware that if you do it with nuage, your users can still connect via FTP and visit the stuff he's not supposed to access (nuage is not your FTP server but just a frontend to it).

> there any built-in option to automatically optimize images being uploaded? 

Yes and it's already built in by default:
- Thumbnails are generated on demand and cache on the browser. Dimensions are 300x300
- Pictures in view mode are resized to match the size of the screen

**Comment by mickael-kerjean** [comment]
Since my previous comment, I've been working on a plugin system for nuage that makes it possible to intercept and change pretty much everything on the backend. When the feature land, it will be possible to create a plugin for your specific requirements:
> Restrict actions so that it's only possible to upload, download, preview, remove or rename files (so no file editing, no creation of new dirs, etc)
> Restrict file types to a whitelist (so that I can allow only png, jpg, etc files to be uploaded)

The idea is the plugin will hook somewhere in the request lifecycle and do things. I have a working demo where the api looks like this:
```
package main

import (	
	. "github.com/mickael-kerjean/nuage/server/common"
	"io"
	"log"
	"net/http"
)

const PRIORITY = 5

func Register() []Plugin {
	return []Plugin{
		{
			Type: PROCESS_FILE_CONTENT_BEFORE_SEND, // where to hook our plugin in the request lifecycle
			Call: hook, // actual function we trigger
			Priority: PRIORITY, // determine execution order whilst multiple plugin type
		},
	}
}

func hook(file io.Reader, ctx *App, res *http.ResponseWriter, req *http.Request) (io.Reader, error){
	log.Println("LOG THIS")
	return file, nil
}
```

This will be compile into a so file (`go build -buildmode=plugin -o test.so index.go`) and drop into the plugin folder.

**Comment by mickael-kerjean** [comment]
As I can't see any action needed from my end here, I'm closing the ticket but feel free to comment back and I'll reopen

**Comment by mickael-kerjean** [comment]
This [giant commit](https://github.com/mickael-kerjean/nuage/commit/ddd1b83b273354194ab5d429fc8390cea47cac11) makes all your use case possible as it allows to programatically intercept and change request. Example of plugin: https://github.com/mickael-kerjean/nuage/blob/master/server/plugin/example/index.go
