### ISSUE TITLE
heroku

### ISSUE THREAD

**Issue by nk932714** [mickael-kerjean/nuage#15]
How to run this repo on heroku. Please make this heroku comaptible.

**Comment by mickael-kerjean** [comment]
Hello,

> Please make this heroku comaptible
If you want to hire me to make it happen, feel free to drop me an email to discuss the details. If you meant doing it for free, I have no need for deploying nuage on Heroku and would prefer to spend my free time on my boat or practicing freediving.

> How to run this repo on heroku
It's just a node application but I didn't invest time to deploy it on Heroku specifically. Shouldn't be hard if Heroku support node application.
If you can make it happen from your end feel free to send a pull request.

**Comment by nk932714** [comment]
thanks for your reply.
