### ISSUE TITLE
Login page: autofill and blocking prompt

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/nuage#18]
Remove default behavior from browsers trying to automatically fill the username and password as it's not very likely to be correct considering our use case ....

From a user standpoint, in its current state, it feels buggy and anarchic

The same applies to the remember me button using a blocking prompt. The prompt trades convenience over smoothness from the user standpoint, we need to get rid of it

**Comment by mickael-kerjean** [comment]
Remove default behavior from browser as it's quite irritating

**Comment by AaronActu** [comment]
Hello Mickael,

Is that (or would it be) possible to autofill fields (like host, username,...) with $_COOKIE or $_SESSION (or at worst, $_GET)?
