### ISSUE TITLE
Readme - WebDAV-fs stream support

### ISSUE THREAD

**Issue by perry-mitchell** [mickael-kerjean/nuage#23]
Hi! Creator of webdav-fs and webdav-client here.. Just thought I'd let you know that `webdav-fs` does indeed [support streams](https://github.com/perry-mitchell/webdav-fs#createwritestreampath-options) 😊

**Comment by mickael-kerjean** [comment]
Hello That's great news!

I'll look into it as I can put aside some time

**Comment by mickael-kerjean** [comment]
All done! Thank for the feature, it works pretty well!
