### ISSUE TITLE
feature: navigation with browser back and forward button

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/nuage#26]

**Comment by mickael-kerjean** [comment]
WIP

**Comment by rinogo** [comment]
Hello! Thanks for such a great project!

Browser button navigation seems to be a little buggy for me. It works great but then stops working seemingly randomly. (Of course, it's probably not random, but I haven't been able to determine how to reliably reproduce the problem).

Once the browser buttons stop functioning, the only reliable way I've found to get them working again is to entirely reload the page (and, therefore, Filestash).

Is there something I'm overlooking? Thanks again!

![image](https://user-images.githubusercontent.com/3732514/74275857-c02ba280-4cb8-11ea-8653-e854fd3ea2ec.png)

**Comment by rinogo** [comment]
Mentioning @mickael-kerjean since I'm not sure if simply commenting on this thread will alert you. 😁 #githubnewb
