### ISSUE TITLE
Dropbox login 400

### ISSUE THREAD

**Issue by tjstankus** [mickael-kerjean/nuage#3]
Attempting to authenticate with Dropbox produces this error:

<img width="647" alt="screen shot 2017-06-21 at 12 23 32 pm" src="https://user-images.githubusercontent.com/41504/27395089-98a19858-567c-11e7-9d51-2e6935faca9a.png">

**Comment by mickael-kerjean** [comment]
Hi there,

Thank you for the report! 
I received a message from dropbox with this [link]( https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/)

Unfortunatly the backend is using the deprecated version and it should explain the issue. 
I'll update the backend asap and reapply for production in the next few days. Hopefully it will be easier to deal with dropbox to apply for production than with google

**Comment by mickael-kerjean** [comment]
It was a pain but it's live

**Comment by tjstankus** [comment]
Wow, thank you for your hard work and quick turnaround. I indeed got through to the Dropbox authentication screen. After allowing access, I was redirected to localhost (127.0.0.1).

**Comment by mickael-kerjean** [comment]
Oups, I should have stop the dev server before deploying it :/
Should be alright now

**Comment by tjstankus** [comment]
Looks good!
