### ISSUE TITLE
Audio Player

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/nuage#40]
play music with an audio widget that stuck in the interface, spotify like

**Comment by mickael-kerjean** [comment]
When touch the surface of the audio thinghy I stumbled upon:
- https://github.com/scottschiller/SoundManager2
- https://github.com/CreateJS/SoundJS

Got no idea yet how it is different than the standard Audio API but it's just here for references when I'll implement it

**Comment by sunjam** [comment]
Hi, I’m curious if you could play nice with this music player, which feels similar to Nuage imo.

[Diffuse](https://www.reddit.com/r/selfhosted/comments/8oarbm/diffuse_a_music_player_which_connects_to_your/) loads music from:
Amazon S3
Azure File/Blob Storage
Dropbox
Google Drive
IPFS
Local Filesystem (native version only)
WebDAV (native version only)

Stores user data on:
LocalStorage (Anonymous mode)
RemoteStorage
Blockstack
More info: https://github.com/icidasset/diffuse

**Comment by mickael-kerjean** [comment]
What do you mean by playing nice? 

As for now I have heavy doubts energy will be put in creating a spotify kindof experience for music, there's already great project that focus just on that. I'm an heavy user of Koel, already looked at Diffuse and those alternative look super sleak.

**Comment by mickael-kerjean** [comment]
I'm closing this, the current Audio player will problably stay as is for now, I don't see the point of reinventing the wheel considering the current alternatives
