### ISSUE TITLE
Share: real time edit

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/nuage#46]
editing could be done collaboratively, for example using something like https://firepad.io/

**Comment by mickael-kerjean** [comment]
I'm closing this as I don't need it and tmux approach is superior. If somebody finds it cool, feel free to reopen

**Comment by Jamesun921** [comment]
need it really !! Many fellows can  write the same doc. And a markdown-previewing can make this software most useful.

**Comment by mickael-kerjean** [comment]
A lot has change since 2018. We now have the ability to switch various implementations of file viewers. What this mean is you can create a plugin that will register its own viewer application for say markdown files so that if you don't agree with the default you can change it. On my end, I can't afford to work full time on this and I have my own roadmap where this feature would be at the bottom of the list so if you want to pick this up, that would be amazing
