### ISSUE TITLE
https://nuage.kerjean.me leads to a redirect loop

### ISSUE THREAD

**Issue by ajyoon** [mickael-kerjean/nuage#55]
Steps to reproduce:

1. Open a new browser window/tab on any webpage
2. Navigate to https://nuage.kerjean.me/
3. (Automatically be redirected to https://nuage.kerjean.me/login)
4. Press back button

Expected result:
* Browser can navigate back to original webpage

Actual result:
* Browser navigates back to https://nuage.kerjean.me/ which then redirects back to https://nuage.kerjean.me/login

I haven't tried it, but I'm guessing this does not happen when the browser has a valid nuage session active.

Seen on Firefox 59.0.2 and Chrome 66.0.3359.139

**Comment by mickael-kerjean** [comment]
Thanks for the report. I'll look into it after work. It should be a straighforward fix.

**Comment by mickael-kerjean** [comment]
The fix has been deployed. feel free to reopen if there's something wrong or found out about other issues

**Comment by ajyoon** [comment]
That did it! Thanks so much for the quick response!
