### ISSUE TITLE
Error while installing in Termux: Android 6.0, Node 8.11.1

### ISSUE THREAD

**Issue by ibnishak** [mickael-kerjean/nuage#61]
> uws@9.14.0 install /data/data/com.termux/files/home/nuage/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0

> node-sass@4.9.0 install /data/data/com.termux/files/home/nuage/node_modules/node-sass
> node scripts/install.js

Downloading binary from https://github.com/sass/node-sass/releases/download/v4.9.0/android-arm64-57_binding.node
Cannot download "https://github.com/sass/node-sass/releases/download/v4.9.0/android-arm64-57_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> nodegit@0.22.0 install /data/data/com.termux/files/home/nuage/node_modules/nodegit
> node lifecycleScripts/preinstall && node lifecycleScripts/install

[nodegit] Running pre-install script
[nodegit] Configuring libssh2.
{ Error: Command failed: /data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/openssl/openssl
/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/libssh2/configure: not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/openssl/openssl' }
/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/libssh2/configure: not found

/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/libssh2/configure: not found

[nodegit] ERROR - Could not finish preinstall
{ Error: Command failed: /data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/openssl/openssl
/data/data/com.termux/files/usr/bin/sh: 1: /data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/libssh2/configure: not found

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/libssh2/configure --with-libssl-prefix=/data/data/com.termux/files/home/nuage/node_modules/nodegit/vendor/openssl/openssl' }

**Comment by mickael-kerjean** [comment]
I never thought someone would even try to install it via termux, I'll give it a try as I got a bit of time, that's definitly an interesting use case!

**Comment by ibnishak** [comment]
IMHO,  this project would be much more useful in a mobile environment where browsing and viewing org files are a pain.  Please do look to it.

**Comment by mickael-kerjean** [comment]
Fully agree and will definitly look at it.

**Comment by mickael-kerjean** [comment]
I'm not termux padawan at all and can't find the libssh2 package which is require as a dependency. Do you know how you can get it from termux?

**Comment by ibnishak** [comment]
`apt list` shows only  libssh and libssh-dev as available packages for termux,  unfortunately.

**Comment by mickael-kerjean** [comment]
I've seen that but it's not good enough for the library that allow git to work. 

I'm investigating the manual compilation path as we speak. If I can't make it work, I'll try the approach to create a script that strip down the git capability.

**Comment by mickael-kerjean** [comment]
I spend hours trying to make it work but I always end up with the same issue after 1hour of compiling. 

I opened [an issue](https://github.com/nodegit/nodegit/issues/1494) upstream, I cross my fingers they will help

**Comment by mickael-kerjean** [comment]
If I don't get an answer from the nodegit contributor, I'll make a script to cut down the git functionality for termux.

**Comment by mickael-kerjean** [comment]
No upstream answer yet, I'm trying the script approach (without git)

**Comment by mickael-kerjean** [comment]
I got it working from my end but it needs a bit of rework (see script in the commit above).

I'm investigating publishing it over to apt or pkg or whatever it is called to make things simple as it's a pain in the butt to create proper build from a touch based keyboard

**Comment by mickael-kerjean** [comment]
I'm closing the ticket but feel free to comment if there's an issue on your termux.

I'm tracking the amount of installation for termux via the install link, if it reaches 50, I'll make it work with `apt install nuage`.

**Comment by ibnishak** [comment]
please provide an uninstall script too

**Comment by mickael-kerjean** [comment]
```
rm -rf /data/data/com.termux/files/usr/share/nuage
rm /data/data/com.termux/files/usr/bin/nuage
```

**Comment by mickael-kerjean** [comment]
Is it working from your end?

**Comment by ibnishak** [comment]
It says webpack not found. Let me install webpack and try again

**Comment by otesuji** [comment]
works on my end

**Comment by mickael-kerjean** [comment]
I made many test from my devices and I can't replicate any error. Can you provide more info?

**Comment by mickael-kerjean** [comment]
I'm closing the ticket as it doesn't seem active.
If there's any struggle during the installation, I'll reopen and be more than happy to assist.
