### ISSUE TITLE
File is cut off

### ISSUE THREAD

**Issue by Nebucatnetzer** [mickael-kerjean/nuage#63]
In one of my org files the bottom is cut off when I open it in nuage. It's only a visual thing however.
Currently I've only tried the demo installation.

Edit: When I collapse the headings I can see the bottom but not when the headings are expanded.

**Comment by mickael-kerjean** [comment]
Hello there, 

thank you for reporting the issue. Can you send a screenshot and provide more information regarding your browser (vendor + version) ?

**Comment by Nebucatnetzer** [comment]
![screenshot from 2018-05-14 22-41-38](https://user-images.githubusercontent.com/2287221/40022563-ac57e232-57c8-11e8-9af3-b73d7519eec1.png)
![screenshot from 2018-05-14 22-42-43](https://user-images.githubusercontent.com/2287221/40022564-ac759e12-57c8-11e8-819b-aab35a08f7ad.png)

The first screenshot shows everything folded and the second one shows the end of the file. As you can see the "Capture" heading is missing.
I'm using Firefox 60 on Linux but noticed the same issue on Firefox on Android.

**Comment by Nebucatnetzer** [comment]
I was able to get the last lines to appear. When I clicked in the last line at bit more white space appeared and I was able to scroll further down. I can reproduce this in a couple of files. However only in this file a line with content is hidden.

**Comment by mickael-kerjean** [comment]
That's interesting. I wasn't able to replicate your problem with any of my org files. Can you send [me](mailto:mickael@kerjean.me) a copy of those org documents?

I've seen a few other Firefox specific bugs as well, I will spend some time this week end to fix those.

**Comment by Nebucatnetzer** [comment]
You're right it's most likely a Firefox related problem.
I tried it today on Chrome and was able to view the file without a problem.

**Comment by mickael-kerjean** [comment]
Awesome thanks!

**Comment by mickael-kerjean** [comment]
I found out the issue is due to different implementation of flexbox. WIP

**Comment by mickael-kerjean** [comment]
I nailed it. Looking at your org file, I've seen quite a few other related issues:
- [x] syntax highlighting: `#+title: blablabla` (always thought the `title` had to be uppercased)
- [x] syntax highlighting: `** CANCELED blabla` (I didn't know it was correct as I usually use `CANCELLED`)
- [ ] the todo view should display the `NEXT` tasks before the `TODO` ones

Another bug I notice is the agenda view won't show many of your date as I thought emacs would always display the current day either as "Mon, Tue, Wed, Thu, Fri, Sat, Sun". I guess I was wrong. Did you enable something in your config to get this behavior? I'll have to make a few tests to make it work properly.

**Comment by mickael-kerjean** [comment]
I've publish the new version live. There's probably another bug depending on how you look at it: As for now, if you edit the deadline or schedule, the day of the week will be written either as "Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun" instead of the localised version you seem to have. 
Is it something that come by default with emacs?

**Comment by Nebucatnetzer** [comment]
Are the changes live on the demo server? I don't have my own yet.

Options can be lowercased since a few versions of org-mode. I wanted to try it out because I would prefer that. However org-mode automatically still creates everything uppercased so I have a bit of a chaos now :).


The CANCELED vs CANCELLED thing is something that I noticed myself as well this week. I think I copied that from somewhere and never really noticed it before. Doesn't really matter however. Seems to be a UK vs. US thing.

The time stamp which have the german weekdays seem to come from my system. I've set it to Swiss German date and number formats but the interface in English. Apparently Ubuntu is not able to show the weekdays in English as well.

**Comment by mickael-kerjean** [comment]
> Are the changes live on the demo server? I don't have my own yet.

I just push it live on the demo server.


All those are perfectly legit, if org mode do it that way, nuage should as well but without getting a report, it's hard to know what's wrong :)

**Comment by Nebucatnetzer** [comment]
Great, now it is working.

I'm happy to provide them :). Nuage could be a great way to work with org files on the go since Orgzly doesn't have webdav sync. In addition it would work on all devices which have a webbrowser.

**Comment by mickael-kerjean** [comment]
> I'm happy to provide them :) 

Would be awesome

> Nuage could be a great way to work with org files on the go 

Right now, everything (file content and the `ls`) is already cache in [indexDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API) and various other mechanism to provide something that is kinda working offline (you just can't save anything without a connection).

**Comment by mickael-kerjean** [comment]
> The time stamp which have the german weekdays seem to come from my system. 

I initially thought it was using the tree first letters but looking at your org document, it doesn't seem to be the case (eg: `Mi`). It's fairly simple to accomodate it, see [here](https://github.com/mickael-kerjean/nuage/blob/master/client/pages/viewerpage/org_viewer.js#L195-L197). Any chance you could send a pull request with the change in your language?
Something like:
```
switch(navigator.language.split("-")[0]){
case "de": ["?", "?", "?", "?"][n]; 
default:
    return ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"][n];
}
```

**Comment by Nebucatnetzer** [comment]
Okay I'll create the PR sometime this week :)     

  

  
  
  
  
  
>
