### ISSUE TITLE
org mode caldav sync?

### ISSUE THREAD

**Issue by poVoq** [mickael-kerjean/nuage#66]
Hi! Really cool project it seems.

Given that you already support WebDAV, has there been any thought put into also allowing org mode to sync with caldav?

It seems there is already something like that for emacs:
https://github.com/dengste/org-caldav

**Comment by mickael-kerjean** [comment]
I've been thinking about it but I'm tear apart between 2 conflicting side:
1. implement all sort of cool stuff that will never be part of the orgmode
2. staying in the scope of org mode where extra features should come as part of the emacs ecosystem, nuage being just a companion

As I see it, in a perfect world, org-caldav would be awesome and there wouldn't be a need for nuage to support caldav properly. I already gave a try to org-caldav but the sync was weird:
- from emacs to caldav: half working but usable
- from caldav to emacs: half working and not really usable to me
- no support for VTODO at all

Maybe it has to do with some missconfiguration from my end but I spent several hours trying to make it work without much success. From a maintenance perspective, I haven't seen 1 message from the original author in there.

@grauschnable seems to be very keen on maintaining the org-caldav project but I'm not sure he even have access to the repo.

@grauschnable: Any thought ?

**Comment by mickael-kerjean** [comment]
It seems @grauschnable is very keen on making orgcaldav awesome. As for now, I'd rather try to contribute his fork.

**Comment by mickael-kerjean** [comment]
If everyone is happy, I'm closing the ticket

**Comment by mickael-kerjean** [comment]
> Would this allow using caldav & org-mode without Emacs?

Not as is, but while I was thinking about a way to bring the awesome export mechanism of org mode, I came to the conclusion that the only solution that could potentially work is to use the real emacs in the backend, loading some sort of lisp code into it and returning the result of the transformation back to the browser. This approach could work as well for caldav and would enable nuage to use pretty much any plugins that was ever created (including org-caldav).
For now this isn't even a WIP
