### ISSUE TITLE
ReferenceError: autoVacuum is not defined

### ISSUE THREAD

**Issue by fngx** [mickael-kerjean/nuage#68]
Hi, I think server is stopping after a while, due to function name/call mismatch in the following file

[/server/model/backend/git.js:l10](https://github.com/mickael-kerjean/nuage/blob/master/server/model/backend/git.js)

setInterval(() => **autoVacuum**, 1000*60*60*10);
[...]

function **autovacuum**(){
[...]
}

Thanks for starting this very neat project.

**Comment by mickael-kerjean** [comment]
Wow you're right, it looks like a nasty typo ....
I'll fix push the fix after work

**Comment by jatupnic** [comment]
Thanks again,

I wasn't much sure which case you'd prefer, so I ended making this change locally.
