### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by ssnjrthegr8** [mickael-kerjean/nuage#70]
Hi, can I contribute by designing a logo for nuage?

**Comment by mickael-kerjean** [comment]
If you feel inspired and think you can get something better, go ahead :)

The current one is pretty much taken straight from flaticon.com with a few minor modifications.

What were you thinking about?

**Comment by ssnjrthegr8** [comment]
I was thinking about a cloud and a folder or a file merged together, for now that's what I have in my mind. Maybe I will come up with another concept. Well I will show you some designs in a few days. If you have any concepts or some idea in your mind feel free to tell me :+1:

**Comment by mickael-kerjean** [comment]
That's a great idea!

If we were to have a new logo, there's just a few things that are important to me:
1. It has to look good at the very small resolution of 16x16 (for the favicon). As I see it, a bad logo would be like the one from [travis-ci](http://travis-ci.org) because I find it hard to know what the favicon represent if you're not already familiar with it.
2. It has to look good when you scale from favicon size up to app icon size and up til 512x512
3. From a license perspective, it has to be compatible with the license of this project (AGPL aka copyleft). I'm nowhere an expert when it comes to licensing, I've just been [reading about it](http://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses)

**Comment by ssnjrthegr8** [comment]
How does this look? I will try encasing the cloud inside a folder or a file later. The important thing is,
do you like this concept? And about licenses, I too am no expert when it comes to licenses but I can only distribute it under Creative Commons Attribution 4.0 license which is non-copyleft and is [compatible with all versions of gnu gpl](http://www.gnu.org/licenses/license-list.html#ccby), but idk if that's good enough...

![nuagev1](https://user-images.githubusercontent.com/38104354/40247059-b9315524-5ae8-11e8-9984-a57ace456cc4.png)

**Comment by ssnjrthegr8** [comment]
Here it is! It is distinguishable even at 16x16 px. 

![g6040](https://user-images.githubusercontent.com/38104354/40269547-c61730c8-5b9d-11e8-8214-dc075e9ff25f.png)

16x16px (When viewed in full screen):

![image](https://user-images.githubusercontent.com/38104354/40269612-78ef7142-5b9e-11e8-949a-30d49d007fbf.png)

![rect6101](https://user-images.githubusercontent.com/38104354/40269658-2e004002-5b9f-11e8-85c1-1ed3cdeaed70.png)

![g6160](https://user-images.githubusercontent.com/38104354/40269659-2e43c2a0-5b9f-11e8-97fb-1e39201582aa.png)

**Comment by mickael-kerjean** [comment]
That's awesome, love it. 
Do you have an SVG version of it? That would help to make a few tests both as an app icon and favicon before pushing live

**Comment by ssnjrthegr8** [comment]
Ofc! Here you go: https://drive.google.com/open?id=1MMpxFKOVl6-Dw87ylBerWWzAy-9LsQh6
Also if you want the logo in different colours like sky blue or something just ask me and I will upload the files to my drive link.

**Comment by mickael-kerjean** [comment]
All good, I'm making a few tests with the one you just sent. was trying a few things:
- change the thickness of the line to make it more clear as a favicon
- create the app icon from it

**Comment by mickael-kerjean** [comment]
I've been reading about logo licensing as well and I'm more confused than when I got started (aka [this article](https://www.crowdspring.com/blog/ask-crowdspring-can-creative-commons-licensed-works-be-used-for-logo-design/)).
As I see it, a logo represent a brand, if it can be reuse elsewhere, it will gives confusion and has some risks I'm not ready to tackle (example if someone create a fork with the same logo that steal people credentials or mine other people computer)

At the end of the day, from what I've read, it seems everyone have their own opinion about the creative common but when it comes to use one for a logo, the only thing I know is I'm not equiped to understand everything it implies from a legal perspective.

**Comment by ssnjrthegr8** [comment]
> was trying a few things

I will do that for you :) Just say how you want the app icon to be - Dimensions, Background Color, Background Shape etc

And about licensing , I will see what I can do about that.

**Comment by mickael-kerjean** [comment]
> I will do that for you :) Just say how you want the app icon to be - Dimensions, Background Color, Background Shape etc

The logo would need to reuse the colors from the app, namely:
```
    --bg-color: #f2f2f2;
    --color: #626469;
    --emphasis: #375160;
    --primary: #9AD1ED;
    --emphasis-primary: #c5e2f1;
    --secondary: #466372;
    --emphasis-secondary: #466372;
    --light: #909090;
    --super-light: #f4f4f4;
    --dark: #313538;
```
In term of dimensions, there's no 1 size fit all. It will end up converted in [many different dimensions](https://github.com/mickael-kerjean/nuage/tree/master/server/public/logo) as it's very device dependent. I guess for now 1024x1024 should be enough as it can be scale down afterward.

**Comment by ssnjrthegr8** [comment]
![path4725](https://user-images.githubusercontent.com/38104354/40366747-91bb27a8-5df5-11e8-8e3f-2ecb178129b6.png)

These are the different versions I came up with and these looked the best. Which one do you prefer? Also for the app icon would you want drop shadows or subtle gradients on it?

![g5967](https://user-images.githubusercontent.com/38104354/40367935-2fd1e948-5df8-11e8-9fcd-a4940836fb90.png)

**Comment by mickael-kerjean** [comment]
It looks awesome but the licensing issue is still here. I would have been more happy to pay for your services but no one has backed the project yet and the current budget is 0$.

**Comment by ssnjrthegr8** [comment]
Payment would not be an issue if you are willing to use my design. Under what license should I share it in order for you to accept it?

**Comment by mickael-kerjean** [comment]
Sorry for the delay, I've been quite busy with the new release aside from my regular job. I'm more than willing to use it, it looks awesome. 

When it comes to licensing, are you willing to go with CC BY?

**Comment by ssnjrthegr8** [comment]
> When it comes to licensing, are you willing to go with CC0?
Yeah I can do that. I guess all that's left to do is the app icon and modifying the favicon. I will update the files and send you a PR soon with all the files.

**Comment by mickael-kerjean** [comment]
Awesome `:)`

**Comment by mickael-kerjean** [comment]
Oups just saw that I closed the issue `:/`, my mistake

**Comment by mickael-kerjean** [comment]
tadaa! Can't thank you enough for this wonderfull gift!
