### ISSUE TITLE
Emacs keybindings

### ISSUE THREAD

**Issue by karlicoss** [mickael-kerjean/nuage#80]
Wondering if there is a way to switch off Emacs keybindings to 'normal' ones, so one could use 'C-x/C-c/C-v/C-s' etc? I'd even be willing to use Emacs keybindings for Nuage only, but for instance C-w (which as far as I understand is 'cut' in emacs), closes the tab in most of the web browsers. Personally, I am using emacs with evil mode, but I do realise vim keybindings are a whole different story :) 

P.S. Thanks for the app, org mode is crucial for my life and time management, and this is gonna make it even easier :)

**Comment by mickael-kerjean** [comment]
Hello again, 

> Wondering if there is a way to switch off Emacs keybindings to 'normal' ones, so one could use 'C-x/C-c/C-v/C-s' 

Right now, no but technically it's possible. It's not there yet for 2 reasons:
- I just use emacs
- I wasn't sure which approach is the best to select keybindings: 
   1. asking user via a popup
   2. define it via the configuration file

 > Personally, I am using emacs with evil mode, but I do realise vim keybindings are a whole different story :)

Not really, I wasn't silly enough to implement the entire text editor by myself and nuage is build on top of CodeMirror. Essentially i've put a lot of customisation that are completly emacs related but with a bit of refactoring, CodeMirror has support for vim as well ([example](https://codemirror.net/demo/vim.html))

> P.S. Thanks for the app, org mode is crucial for my life and time management, and this is gonna make it even easier :)

That's great to hear! If you have some more ideas, feel free to share `:)`

**Comment by mickael-kerjean** [comment]
Done, instead of polluting the UI with a popup requesting which editor someone prefers, I've added the settings in [here](https://github.com/mickael-kerjean/nuage/blob/master/config_client.js#L3)

> for instance C-w (which as far as I understand is 'cut' in emacs), closes the tab

You're right, unforunalty, this behavior can't be prevented in js land and browser vendors don't intent to provide a way to change that ....
The trick i to make a shortcut to your desktop (which is the way I'm using it), in chromium it's under settings -> more tools -> Add to desktop

**Comment by karlicoss** [comment]
Hi! I just checked and this worked, thanks!

One thing; so it's configured in `config_client.js` -- that essentially means that the setting is hardcoded for the instance you are running (https://nuage.kerjean.me/login), right? E.g. I had to run it locally so I could change it to vim and check it out. I guess it makes perfect sense if you are self-hosting (which I was planning to try out anyway), but if you indend your instance as a demo might be good idea to make it more dynamic.

**Comment by mickael-kerjean** [comment]
>  essentially means that the setting is hardcoded for the instance you are running, right?

Correct

> as a demo might be good idea to make it more dynamic

Fully agree but I'm not sure what's the best way to integrate it from a UI perspective. Any ideas? As I see it now, more buttons would mean unecessary bloat, a poup would be intrusive and a keyboard shortcut quite hard to find out.

**Comment by karlicoss** [comment]
I think ultimately as you add more features you'd need some sort of global
settings UI, so perhaps it belongs there?

**Comment by mickael-kerjean** [comment]
Short term I don't have much better ideas but long term, there will be some sort of user settings which would be a perfect fit for this feature. As we speak, I can't put my head around how it can be integrated in the UI.

**Comment by karlicoss** [comment]
Sure. It's okay, like I said I am hoping to self-host anyway. I was rather worried about the people trying out your demo and finding keybindings uncomfortable :) 
Thanks again!
