### ISSUE TITLE
Prompt to save on closing a note

### ISSUE THREAD

**Issue by karlicoss** [mickael-kerjean/nuage#81]
Right now when you close the tab or click on parent directory and got unsaved content, modifications will just get discarded. It might be a good idea to prompt user for saving first.

**Comment by mickael-kerjean** [comment]
That's a great idea. I'm currently working on a different [set of features](https://github.com/mickael-kerjean/nuage/wiki/ROADMAP-for-Release-0.2:-Photo-Management) bit will definitly made it happen once I'm done with those one first

**Comment by mickael-kerjean** [comment]
All done, can you test it from your end?

**Comment by karlicoss** [comment]
Awesome, that worked! Thanks for a quick fix :+1:
