### ISSUE TITLE
Feature request: SSE-C S3 (Minio) support

### ISSUE THREAD

**Issue by arno01** [mickael-kerjean/nuage#90]
Please add a possibility of providing Nuage with the S3's``X-Amz-Server-Side-Encryption-Customer-Key`` (32 bytes), per-path, so the encrypted content can be viewed.

https://docs.minio.io/docs/how-to-use-minio-s-server-side-encryption-with-aws-cli
https://docs.aws.amazon.com/AmazonS3/latest/dev/ServerSideEncryptionCustomerKeys.html

**Comment by mickael-kerjean** [comment]
Hello, 

I will look after this feature once done with [this](https://github.com/mickael-kerjean/nuage/issues/87) and would gladly accept a pull request with this feature

**Comment by mickael-kerjean** [comment]
I'm working on that as we speak but I get weird errors using minio on my testing instance: https://minio.kerjean.me

I got the encryption working fine with S3 but minio is complaining:
```
InvalidRequest: Requests specifying Server Side Encryption with Customer provided keys must be made over a secure connection.\n\tstatus code: 400, request id: 1546BC5961507CD0, host id: 
```
Well it's using SSL behind a reverse proxy, isn't it enough? Do you have a properly setup one with encryption working I could use for testing?

**Comment by arno01** [comment]
Hi @mickael-kerjean , thank you for starting looking into this!

So, in order for Minio to make use of the SSE-C (Server Side Encryption with Customer provided keys) is to make Minio understand it is secured by the TLS. Unfortunately, having the TLS terminated only at the reverse proxy is not enough. Or maybe fortunately, since this is to ensure the customer provided keys are not being scattered across the internet or the intranet in the plain-text. In other words, there is no secure way for the Minio to know it is behind the TLS unless telling that to Minio directly. And the only way Minio can know that is running in a TLS mode for SSE-C to get working is by adding ``/root/.minio/certs/public.crt`` & ``/root/.minio/certs/private.key`` files, can be self-signed, but then the reverse proxy should either trust self-signed (not verify the minio backend certs), or self-signed cert should be generated with a self-signed CA cert which the reverse proxy will be trusting. You can reuse my [gencert script](https://git.nixaid.com/arno/gencert) which will automatically do that.

## References

- https://github.com/minio/minio/issues/6093
- https://github.com/minio/minio/issues/6125

**Comment by mickael-kerjean** [comment]
> is to make Minio understand it is secured by the TLS.

That's what I thought, was just kinda lazy to configure a ready to prod instance of a product I don't have a use of just to get this feature up and running.

> can be self-signed

Good news then, will try that out

**Comment by mickael-kerjean** [comment]
I've made some test using both ssl and an encryption key. Everything looks fine to me. I'm closing this but feel free to comment back and I'll reopen
