### ISSUE TITLE
Ignoring config_client.js

### ISSUE THREAD

**Issue by bdillahu** [mickael-kerjean/nuage#91]
I'm sure this is my setup, somehow, but looking to see if anybody has a hint on how to debug it...

Docker based, self-hosted (on unRaid if that matters)... all works fine as near as I can tell, but if I modify (or even remove) config_client.js, nothing changes. 

It's like it's not even using the file.

Seems the hierarchy is right... paths from references to that file from elsewhere in the code appear correct.

Not sure how to approach it. If somebody has a thought, let me know :-)

Thanks!

**Comment by mickael-kerjean** [comment]
Hello,

I have a good and a bad news. The bad news is right now, changing the config_client.js needs a recompile to take into effect (aka `NODE_ENV=production npm run build`). The reasons is lazyness from my end as I'm undertaking a major rework of the backend from NodeJS to Golang. That's where the good news comes in, the rewrite of this repo is almost complete, and this is the kind of things that will be address on the new release which will be out before the end of this week.

**Comment by bdillahu** [comment]
Ah, ok, no problem... at least I know not to sit here trying to "fix" it :-) - Appreciate the work and look forward to the rework...

**Comment by andyjhall** [comment]
Should this fix now be live? Pulled down the docker image today and still not working

**Comment by mickael-kerjean** [comment]
Hoo I just push before to go to bed, didn't expect somebody would see this in such a short amount of time. Will work before the end of the day  `:)`

**Comment by andyjhall** [comment]
Still doesn’t seem to be working even on ur latest commit, should the docker build now be working?

**Comment by mickael-kerjean** [comment]
Yes it should, do you have the new version? 
```
docker pull machines/nuage
```

**Comment by andyjhall** [comment]
Apologies, this is now working, I must not of pulled the latest image.

**Comment by mickael-kerjean** [comment]
All good `:)`, don't hesitate to send feedback, bring up idea or even code
