### ISSUE TITLE
Password not hidden

### ISSUE THREAD

**Issue by bdillahu** [mickael-kerjean/nuage#94]
It appears that if you put in a password (for example for a git connection), it replaces it with dots... but if you go to the page and then use a browser "back" button or browser reload you can see the password.

Security issue I think, although not sure how critical.

**Comment by mickael-kerjean** [comment]
I'll look into it, the problem is browser don't have a password version of a textarea (for privat e key).

**Comment by mickael-kerjean** [comment]
done, the bug was only affecting browser that don't support the `text-security` css property
