### ISSUE TITLE
Connection Question

### ISSUE THREAD

**Issue by andyjhall** [mickael-kerjean/nuage#95]
Are connections (via Sftp as an example) made from the server side Or the client side? I would like to leave the actual sftp server behind a firewall

**Comment by mickael-kerjean** [comment]
Server side

> I would like to leave the actual sftp server behind a firewall

No problem with that which can very usefull in an enterprise settings with restrictive proxy and no way to get throught anything else than HTTP. Out of the enterprise though, I don't really do it as it would waste my awesome welcome screen:
```
 sftp -P 2222 "mickael@kerjean.me"@files.kerjean.me
mickael@kerjean.me@files.kerjean.me's password: 

*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^         ,---/V\
`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.    ~|__(o.o)
^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'^`*.,*'  UU  UU
Connected to mickael@kerjean.me@files.kerjean.me.
sftp> 

```

**Comment by mickael-kerjean** [comment]
I'm closing this as I can't see any actions that needs to be done or activity. Feel free to comment again and I'll reopen
