### ISSUE TITLE
Stuck on Spinner

### ISSUE THREAD

**Issue by palitu** [mickael-kerjean/nuage#97]
I have installed it using Docker, on my home Ubuntu 18.04 server.

However, it doesn't matter where i deploy it, I only ever get a spinner.

When i hit the API directly, i get what looks like apropriate JSON - 

`{"status":"ok","results":[{"name":"leigh","type":"directory","size":4096,"time":1532955138000},{"name":".directory","type":"file","size":44,"time":1512048606000}],"metadata":null}`

But I cannot work out what else i can do to debug (ie set logging levels inside the container), or workout what the issues actually are.

any guidance would be great!

cheers,

**Comment by mickael-kerjean** [comment]
Did you try flush your cookies? Which browsing are you using? Can you send a link?

**Comment by palitu** [comment]
I am using Chrome and Opera.  I have flushed the cache, looking at chromes console i get this:

![image](https://user-images.githubusercontent.com/6634784/43746130-ed7aec80-9a14-11e8-8577-9320dbba9000.png)

I have created a user for you, but will PM it to you.

**Comment by mickael-kerjean** [comment]
Definitly a bug

**Comment by palitu** [comment]
I have emailed you.

**Comment by palitu** [comment]
Ah cool - i just looked at you commit.  I will await the new docker image and let you know how it goes.

Thanks for the quick turn around!

**Comment by palitu** [comment]
and updated - thanks

**Comment by mickael-kerjean** [comment]
Yes I've seen your email, that's how I was able to replicate the problem both in your environment and my machine. 

> I will await the new docker image

The build is complete and has been updated on the docker hub, you should be able to get the patch by pulling the new version:
```
docker pull machines/nuage
```

Can you say if it's better now?

> Thanks for the quick turn around!

I'm about to go on leave taking my parents on the east coast, would have been sad to leave  with something broken :(

**Comment by palitu** [comment]
Yep, that has foxed it - well done and thank you.

Are you in Australia too? I saw a photo that looked like it was in Melbourne.  And the timezones are matching.  Im in Perth.

edit - yep definitely Melbourne!

**Comment by mickael-kerjean** [comment]
That's good news then! 
Not Melbourne but Sydney. So nice, my girlfriend just come back from a Perth to Broome trip, need to do it as well!
