### ISSUE TITLE
Feature request: Connect S3/Webdav using JS in local browser

### ISSUE THREAD

**Issue by xiaolei0125** [mickael-kerjean/nuage#98]
Is there a way to connect directly to cloud storage using JS in local browser, No need to pass data through the server ?
There are two advantages:
1. Using static web page to hosting nuage, smaller cost;
2. Network traffic from lcoal browser directly to cloud storage， no need to pass through server which can save traffic and faster.

**Comment by mickael-kerjean** [comment]
My dream would be to ditch the server completly. However this approach would severly limit what can be achieve. The only backend that would still be operational would be S3, Dropbox and Google Drive. In theory if configured for this specific case (with some CORS headers) Webdav could work half the time but most actions wouldn't be possible.

The state of the web browsers isn't advanced enough for a web application to directly connect to a backend via FTP, SFTP, Git or Webdav, it needs some man in the middle (the server) that can access the network stack without filtering. The day browser support native socket, this would be possible but considering the security implication, it will probably never happen

**Comment by xiaolei0125** [comment]
Ok, I understand.  Thanks for you reply.
