### ISSUE TITLE
publish codemirror mode to npm

### ISSUE THREAD

**Issue by mickael-kerjean** [mickael-kerjean/nuage#99]
as requested by @ryanpcmcquen [here](https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/issues/3)

**Comment by ryanpcmcquen** [comment]
@mickael-kerjean, is it working now?

**Comment by mickael-kerjean** [comment]
When it comes to orgmode, I will deprecate codemirror in favor of more flexible libraries (i'm POCing around a few like slate as we speak). Codemirror was a great lib to ship something quickly but I'm starting to hit the nail trying to reach the experience of Dropbox paper or akin editor.

**Comment by ryanpcmcquen** [comment]
Cannot wait to see what you go with!

**Comment by mickael-kerjean** [comment]
:)
